### ISSUE TITLE
orgmode with org-bullets.nvim

### ISSUE THREAD

**Issue by YuCao16** [akinsho/org-bullets.nvim#18]
Hi, just a quick question, I was using orgmode with org-bullet, headline works before. After yesterday's update the headline is not displaying properly, I noticed you just updated something, I changed the setup but my headline is still not displaying properly, do I need to change any other settings please?
<img width="588" alt="image" src="https://user-images.githubusercontent.com/62466929/173654626-563b4340-07a6-44bd-b496-77c495392fd0.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/62466929/173653820-482b7663-4976-4f6b-bfe3-6a7ec90f9c00.png">

**Comment by akinsho** [comment]
@YuCao16 if everything is update, and you are using the treesitter parser then it should be working fine you don't need to specify symbols on purpose if you are happy with the defaults

**Comment by YuCao16** [comment]
> @YuCao16 if everything is updated, and you are using the treesitter parser then it should be working fine you don't need to specify symbols on purpose if you are happy with the defaults

I updated everything yesterday but the headline was still not working, but I just updated to the latest commit and now the headline is showing properly again, thank you very much for the update.
